# Generated by Django 4.0.6 on 2022-07-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_csm_css'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmsslider',
            old_name='csm_css',
            new_name='cms_css',
        ),
    ]
